### ISSUE TITLE
SEO and meta-tag specificity

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.org#104]

**Comment by jakehlee** [comment]
There may be a benefit to implementing this (< 1hr) so that the site unfurls on Slack, etc. when linked. 

e.g. https://whitep4nth3r.com/blog/level-up-your-link-previews-in-slack/

**Comment by jakebox** [comment]
@hibaa8 If you want a challenge feel free to make a branch and give this a try.
