### ISSUE TITLE
FAQ on how to join

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.org#55]
Website needs a section on how to actually join the club

**Comment by jakehlee** [comment]
We should probably put our weekly meeting schedule somewhere on the website. An additional jumbotron section underneath the existing three makes sense. I'll look into it.

**Comment by leee** [comment]
i continue to maintain that jumbotrons are terrible :^)

**Comment by jakehlee** [comment]
Instructions added in #92
