### ISSUE TITLE
[2016-09-24 01:49:46] ERROR `/assets/media/img/rascal2.jpg' not found.

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.org#56]
for http://columbiaspace.org/rascal/2016/04/01/rasc-al-mission-success/

**Comment by jakehlee** [comment]
Found it. Fixing now

**Comment by jakehlee** [comment]
Error came from moving images dumped in 

> /assets/media/img/

 into 

> /assets/media/img/posts
