### ISSUE TITLE
Mission Labeling for Outreach and Operations

### ISSUE THREAD

**Issue by albee** [columbiaspace/columbiaspace.org#57]
Outreach and Operations should have some sort of distinction from Missions (which are technical) in the Missions tab. Maybe a line break?

**Comment by leee** [comment]
would it make sense to have them under missions? this may be a good time to have the board+GB convene and discuss the way the website is currently structured/organized. e.g. perhaps rename the members pill tab to operations, and on that dropdown menu, have a link to each "administrative" mission an <hr>, and then the list of members.

**Comment by leee** [comment]
@jakehlee

**Comment by jakehlee** [comment]
I would prefer to put Outreach outside the dropdown; same thing with operations. I'm pretty sure we have enough room for that. Perhaps a separate dropdown for administrative aspects? Or give them individual spots on the navbar? I'll think about it.

Divider currently indicates an inactive mission so it's probably not a good idea. Too many dividers get confusing.

**Comment by leee** [comment]
So does this mean we're operations? :^)

okay, how about this - an `Inactive Missions` link to a page filled with links to the missions.

**Comment by jakehlee** [comment]
Missions dropdown is currently satisfactory, ops-outreach are operating closer to missions capacity
