### ISSUE TITLE
Smooth scrolling button

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.org#59]
Clicking "About Us" on the front page should scroll down smoothly - was going to use this for scrolling to the join us section. Probably just a js issue?

**Comment by jakehlee** [comment]
@richards in 7706c1 the smooth scrolling got commented out (it wasn't working anyways), do we want to put it back in? 

It basically scrolls the page down to the about section if someone clicks on it from the about page.

**Comment by jakehlee** [comment]
nvmd, JUST saw we have an entirely new "about" page now

**Comment by richards** [comment]
Yeah I thought considering how much additional text we have it would be better to just give About it's own page
