### ISSUE TITLE
Front page revamp

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.org#98]
- [ ] Remove 3 image jumbotrons
- [ ] Move newsletter signup below (or within) abstract section
- [ ] Three columns in a jumbotron afterwards
  - Facebook Page Plugin with Events tab (https://developers.facebook.com/docs/plugins/page-plugin)
  - Most Recent Blog Post
  - Most Recent Press Example
- [ ] Slack join button (general signup), right-justified on abstract title row

**Comment by jakehlee** [comment]
Slack join button should also be added to the abstract title row of mission pages - however, these will link directly to specific channels within the slack server.

**Comment by jakebox** [comment]
Front page has been updated, closing so future changes can get a new issue
